### ISSUE TITLE
Limit java heap size

### ISSUE THREAD

**Issue by saaj** [cnadiminti/docker-dynamodb-local#1]
Currently after just a few interactions with local DynamoDB its java process' memory usage becomes ~2GiB. It looks like a serious waste of memory for a SQLite wrapper. There are two options:
1) Set reasonable default, e.g. `-Xmx256m` works fine
2) Provide a way for override java config through passing an environment variable to the container

**Comment by cnadiminti** [comment]
First of all, thanks for using this image and posting the very first issue in this repository. 

How about using the `_JAVA_OPTIONS` environment variable?
For ex: `docker run -e _JAVA_OPTIONS='-Xmx256m' cnadiminti/dynamodb-local:latest`

**Comment by saaj** [comment]
To me it looks like `_JAVA_OPTIONS` carries some internal meaning as it starts with underscore. I don't know Java conventions, but it [is used along other variables](https://stackoverflow.com/q/28327620/2072035). From them I would prefer `JAVA_OPTS`, which is also shorted to write.

Thanks for a useful image. Previously I used `peopleperhour/dynamodb` but couldn't give this feedback, so I switched to yours.

**Comment by cnadiminti** [comment]
@saaj Please pull the latest images, verify and let us know.

**Comment by saaj** [comment]
`JAVA_OPTS` works like a charm. Thank you.

**Comment by cnadiminti** [comment]
Thanks for the confirmation.
