### ISSUE TITLE
2020-01-24 is broken?

### ISSUE THREAD

**Issue by leppaott** [cnadiminti/docker-dynamodb-local#10]
2020-01-24 (2019-02-07/Dockerfile) tag is still on 2019.

**Comment by cnadiminti** [comment]
Looks like. Thanks, @leppaott  for bringing it up. Will fix it soon

**Comment by cnadiminti** [comment]
You should be good now with b690100. Please confirm.
Please note that the builds are still pending for the newer tags in docker-hub right now.
