### ISSUE TITLE
Add inMemory option

### ISSUE THREAD

**Issue by pauljamescleary** [cnadiminti/docker-dynamodb-local#6]
Could you expose an environment variable whereby we can indicate that we want inMemory only?

**Comment by cnadiminti** [comment]
First of all, sorry for the late response. I was on vacation for more than a month.

You can always overwrite CMD. Did you try something like `docker run --rm -p 8000:8000 cnadiminti/dynamodb-local:latest -inMemory` ?

**Comment by pauljamescleary** [comment]
No worries, no urgency.

I was trying to wholesale just use your docker image without overwriting anything in the docker file.  I will try the `-inMemory` thing

**Comment by cnadiminti** [comment]
Cool. Would wait for your confirmation then

**Comment by cnadiminti** [comment]
@pauljamescleary I'm closing as its more than couple of weeks. Please feel free to reopen if needed.
