### ISSUE TITLE
2018-04-11 is broken

### ISSUE THREAD

**Issue by huguesb** [cnadiminti/docker-dynamodb-local#7]
`/docker-entrypoint.sh` is missing the eXecute permission

**Comment by cnadiminti** [comment]
@huguesb Thanks for reporting. Will fix soon.

**Comment by cnadiminti** [comment]
@huguesb Please take a look at the [fix](https://github.com/cnadiminti/docker-dynamodb-local/commit/7590b7e0a763681ad9a9083f6bfe65df08dee51f) and verify. Should be good now.

**Comment by huguesb** [comment]
LGTM. Did you update the image on docker hub?

**Comment by cnadiminti** [comment]
Automated build is enabled. Please take a look [here](https://hub.docker.com/r/cnadiminti/dynamodb-local/builds/)
