### ISSUE TITLE
Checksum verification

### ISSUE THREAD

**Issue by razor-x** [cnadiminti/docker-dynamodb-local#8]
The downloaded tar files should be checked against the corresponding sha256 checksum provided by Amazon here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

It should be enough to download the sha256 file and verify on build before extraction.

**Comment by razor-x** [comment]
Something like this should work:

```
RUN curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_${DYNAMODB_VERSION}.tar.gz && \
    curl -O https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_${DYNAMODB_VERSION}.tar.gz.sha256 && \
    sha1sum -c dynamodb_local_${DYNAMODB_VERSION}.tar.gz.sha256 && \
    tar zxvf dynamodb_local_${DYNAMODB_VERSION}.tar.gz && \
    rm dynamodb_local_${DYNAMODB_VERSION}.tar.gz
```

**Comment by sowjanyamanne** [comment]
Sounds good. I'll enhance it ASAP.
Thanks for reporting it @razor-x

**Comment by cnadiminti** [comment]
Fixed [here](https://github.com/cnadiminti/docker-dynamodb-local/commit/08bc8625d3c82662300d28e74f520a05354e034c) 

A quick note,
I see  [here](https://s3-us-west-2.amazonaws.com/dynamodb-local/) that *.tar.gz.sha256 is not available for versions older than 2016-04-19.
